CREATE TABLE IF NOT EXISTS users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR(255) UNIQUE,
    user_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    available   BOOLEAN,
    users_id    BIGINT REFERENCES users (id),
    description VARCHAR(255),
    name        VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP(6),
    end_date   TIMESTAMP(6),
    status     VARCHAR(255),
    booker_id  BIGINT NOT NULL REFERENCES users (id),
    items_id   BIGINT NOT NULL REFERENCES items (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created   TIMESTAMP(6),
    text      VARCHAR(255),
    author_id BIGINT REFERENCES users (id),
    items_id  BIGINT REFERENCES items (id)
);





