CREATE TABLE IF NOT EXISTS ITEM
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_name   VARCHAR(100)                            NOT NULL,
    description VARCHAR(100),
    owner_id    BIGINT                                  NOT NULL,
    available   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT
);

CREATE TABLE IF NOT EXISTS users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255)                            NOT NULL,
    email     VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);